### ISSUE TITLE
"error": "authentication session not found"

### ISSUE THREAD

**Issue by xelfe** [int128/kubernetes-dashboard-proxy#2]
Hi ! I did installation from the README and also from [there](https://itnext.io/protect-kubernetes-dashboard-with-openid-connect-104b9e75e39c ) a couple of time and it's never work. The only thing i've change is adding kubernetes.io/ingress.class: nginx and kubernetes.io/tls-acme: "true" to annotations of dashboard-kubernetes-proxy  for resolving the domain.
The login keycloak appear but when I login I got error 502 Bad Gateway from my browser.

If I look into the pods logs of the proxy I got;
 
```
info	starting the service	{"prog": "keycloak-proxy", "author": "Rohith", "version": "v2.2.2 (git+sha: ff204ed, built: 03-07-2018)"}
info	attempting to retrieve configuration discovery url	{"url": "https://keycloak.xxx.com/auth/realms/master", "timeout": "30s"}
info	successfully retrieved openid configuration from the discovery
info	enabled reverse proxy mode, upstream url	{"url": "https://kubernetes-dashboard.kube-system.svc.cluster.local"}
info	using session cookies only for access and refresh tokens
info	protecting resource	{"resource": "uri: /*, methods: DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT,TRACE, required: authentication only"}
info	keycloak proxy service starting	{"interface": "0.0.0.0:3000"}
error	no session found in request, redirecting for authorization	{"error": "authentication session not found"}
info	issuing access token for user	{"email": "xxx@xxx", "expires": "2018-08-09T18:00:10Z", "duration": "59.296666348s"}
error	no session found in request, redirecting for authorization	{"error": "authentication session not found"}

```

Any idea of what's wrong ?

**Comment by xelfe** [comment]
I dit it work. Just had to put ingress stuff into kubernetes-dashboard-proxy.yaml like so;

```
proxy:
  oidc:
    redirectURL: https://dashboard.xxx.com

    ## using Keycloak
    discoveryURL: https://keycloak.xxx.com/auth/realms/kubernetes
    clientID: kubernetes
    clientSecret: x8x21x82-a3x0-xxe4-b4xe-5d03x0ax5fx8

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - dashboard.xxx.com
  tls:
   - secretName: dashboard-proxy-tls
     hosts:
       - dashboard.xxx.com
```

**Comment by brnavneet** [comment]
Hi xelfe ,

I am getting same error, Could you please elaborate what changes you made to ingress?

**Comment by brnavneet** [comment]
found the issue!
By checking nginx-ingress-controller logs
kubectl logs --follow -n kube-system deployment/nginx-ingress-controller

got below error 
[error] 23559#23559: *1369655 upstream sent too big header while reading response header from upstream, client:

to resolve Add annotation to increase buffer size
annotations:
  nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"

It worked for me :)
